language: python
python:
  - "3.6"
# command to install dependencies
install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - 'pipenv sync --dev'
# commands to compile messages, run tests, etc
script:
  - python manage.py compilemessages
  - python manage.py test --settings=bakery_payments_v2.settings.testing