language: python
dist: bionic
python:
  - "3.10.2"
# command to install dependencies
install:
  - 'pip install -r requirements.txt'
  - 'pip install -r requirements-dev.txt'
# commands to compile messages, run coverage, etc
script:
  - python manage.py compilemessages
  - flake8
  - pycodestyle
  - coverage run --source='.' manage.py test --settings=bakery_payments_v2.settings.testing
  - coverage report
# send coverage report to coveralls.io
after_success:
  - coveralls
