language: python
dist: xenial
python:
  - "3.8.0"
# command to install dependencies
install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - 'pipenv sync --dev'
# commands to compile messages, run coverage, etc
script:
  - python manage.py compilemessages
  - flake8
  - pycodestyle
  - coverage run --source='.' manage.py test --settings=bakery_payments_v2.settings.testing
  - coverage report
# send coverage report to coveralls.io
after_success:
  - coveralls