version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: bakery
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    environment:
      DB_HOST: 'db'
    ports:
      - "3000:3000"
      - "8001:8001"
    depends_on:
      - db