version: '3'

services:
  db:
    image: postgres
    container_name: bakery-payments-db
    environment:
      - POSTGRES_DB=bakery
  web:
    image: python:3.6.8
    container_name: bakery-payments-web
    build: .
    environment:
      - DB_HOST=db
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db