[tool.black]
line-length = 120
target-version = ['py310']

[tool.coverage.run]
branch = true
omit = [
    "*/migrations/*",
    "*/settings/production.py",
    "*/static/*",
    "manage.py"
]

[tool.coverage.report]
fail_under = 90
