# Generated by Django 2.1.5 on 2019-02-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
