# Generated by Django 2.1.5 on 2019-02-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-id'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
