name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install gettext
        run: sudo apt install gettext
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python environment
        uses: actions/setup-python@v3.0.0
        with:
          python-version: '3.10.2'
      - name: Check Python version
        run: python --version
      - name: Install requirements
        run: | 
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Compile messages
        run: python manage.py compilemessages
      - name: Check code convention
        run: |
          flake8
          pycodestyle
      - name: Run coverage      
        run: |     
          coverage run --source='.' manage.py test --settings=bakery_payments_v2.settings.testing
          coverage report
        
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
